
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 03 12:52:55 EST 2018
//----------------------------------------------------

package smpl.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 30;
  public static final int DQUOTES = 15;
  public static final int POW = 21;
  public static final int SQUOTES = 14;
  public static final int CONCAT = 56;
  public static final int PERIOD = 11;
  public static final int READINT = 42;
  public static final int CASE = 55;
  public static final int CAR = 37;
  public static final int INTEGER = 60;
  public static final int NOTEQUAL = 34;
  public static final int CDR = 38;
  public static final int LPAREN = 2;
  public static final int PRINTLN = 40;
  public static final int PAIRCHECK = 36;
  public static final int LCBRACE = 6;
  public static final int MINUS = 17;
  public static final int RCBRACE = 7;
  public static final int CHARACTER = 61;
  public static final int RPAREN = 3;
  public static final int SEMICOLON = 10;
  public static final int LESSEQUAL = 32;
  public static final int NIL = 59;
  public static final int LESSTHAN = 31;
  public static final int LAZY = 47;
  public static final int COMMA = 8;
  public static final int CALL = 46;
  public static final int BAND = 23;
  public static final int DIV = 19;
  public static final int BNOT = 25;
  public static final int PLUS = 16;
  public static final int IF = 52;
  public static final int ASSIGN = 22;
  public static final int EOF = 0;
  public static final int LNOT = 26;
  public static final int LAND = 27;
  public static final int EQUAL = 29;
  public static final int TRUE = 57;
  public static final int ISEQUAL = 50;
  public static final int error = 1;
  public static final int MUL = 18;
  public static final int LOR = 28;
  public static final int MOD = 20;
  public static final int PAIR = 35;
  public static final int GREATEREQUAL = 33;
  public static final int COLON = 9;
  public static final int ISEQUIVALENT = 51;
  public static final int ELSE = 54;
  public static final int BOR = 24;
  public static final int LBRACE = 4;
  public static final int VARIABLE = 62;
  public static final int READ = 41;
  public static final int LIST = 43;
  public static final int SUBSTR = 44;
  public static final int LET = 48;
  public static final int THEN = 53;
  public static final int RBRACE = 5;
  public static final int LVECTOR = 12;
  public static final int RVECTOR = 13;
  public static final int PROC = 45;
  public static final int DEF = 49;
  public static final int FALSE = 58;
  public static final int PRINT = 39;
}

